## Reworking dataset for data visualization
### Transforming a dataset to improve data visualization in Tableau using Python and Pandas library

* Used for this Tableau visualization: https://public.tableau.com/app/profile/contato/viz/Renewablesenergyanalysis/Dashboard1
* Original dataset by **Our World in Data**: https://www.kaggle.com/datasets/pralabhpoudel/world-energy-consumption


Datasets can be used just 'out of the box' for dashboards and general data visualizations but most of the time, they are not in the best way to create them. 

Here, I rework the dataset ['World Energy Consumption' created by Our World in Data](https://www.kaggle.com/datasets/pralabhpoudel/world-energy-consumption) for my dashboard in Tableau. I tried doing it with the original format but, in order to have interesting tooltips and more advanced charts, I decided it would be easier to have it in a different way.

Below I show step by step of this rework using Pandas library.


#### Importing the dataset

In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/world-energy-consumption/World Energy Consumption.csv

#### Transforming it to Pandas DataFrame

In [2]:
import pandas as pd

df0 = pd.read_csv('/kaggle/input/world-energy-consumption/World Energy Consumption.csv')

df0

,iso_code,country,year,coal_prod_change_pct,coal_prod_change_twh,gas_prod_change_pct,gas_prod_change_twh,oil_prod_change_pct,oil_prod_change_twh,energy_cons_change_pct,...,solar_elec_per_capita,solar_energy_per_capita,gdp,wind_share_elec,wind_cons_change_pct,wind_share_energy,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_energy_per_capita
0,AFG,Afghanistan,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,1901,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,1902,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,1903,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,1904,NaN,0.000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17427,ZWE,Zimbabwe,2015,-25.013,-10.847,NaN,NaN,NaN,NaN,-0.789,...,0.579,NaN,2.503057e+10,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17428,ZWE,Zimbabwe,2016,-37.694,-12.257,NaN,NaN,NaN,NaN,-14.633,...,0.641,NaN,2.515176e+10,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17429,ZWE,Zimbabwe,2017,8.375,1.697,NaN,NaN,NaN,NaN,NaN,...,0.773,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17430,ZWE,Zimbabwe,2018,22.555,4.952,NaN,NaN,NaN,NaN,NaN,...,0.970,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
17431,ZWE,Zimbabwe,2019,-35.015,-9.422,NaN,NaN,NaN,NaN,NaN,...,0.956,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN

#### Filtering dataset with the columns I will use only

In [3]:
df0 = df0[['iso_code', 
           'country', 
           'year',
           'biofuel_electricity', 
           'hydro_electricity',
           'nuclear_electricity',
           'solar_electricity',
           'wind_electricity', 
           'other_renewable_electricity',
           'coal_electricity',
           'gas_electricity',
           'oil_electricity',
           'biofuel_elec_per_capita', 
           'hydro_elec_per_capita',
           'nuclear_elec_per_capita',
           'solar_elec_per_capita',
           'wind_elec_per_capita', 
           'coal_elec_per_capita',
           'gas_elec_per_capita',
           'oil_elec_per_capita',
           'population'
          ]]

df0

,iso_code,country,year,biofuel_electricity,hydro_electricity,nuclear_electricity,solar_electricity,wind_electricity,other_renewable_electricity,coal_electricity,...,oil_electricity,biofuel_elec_per_capita,hydro_elec_per_capita,nuclear_elec_per_capita,solar_elec_per_capita,wind_elec_per_capita,coal_elec_per_capita,gas_elec_per_capita,oil_elec_per_capita,population
0,AFG,Afghanistan,1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5021241.0
1,AFG,Afghanistan,1901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5053439.0
2,AFG,Afghanistan,1902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5085403.0
3,AFG,Afghanistan,1903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5118005.0
4,AFG,Afghanistan,1904,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5150814.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17427,ZWE,Zimbabwe,2015,0.128,4.940,0.0,0.008,0.0,0.128,4.312,...,0.0,9.265,357.582,0.0,0.579,0.0,312.109,0.0,0.0,13815000.0
17428,ZWE,Zimbabwe,2016,0.147,2.955,0.0,0.009,0.0,0.147,3.715,...,0.0,10.478,210.620,0.0,0.641,0.0,264.781,0.0,0.0,14030000.0
17429,ZWE,Zimbabwe,2017,0.151,3.929,0.0,0.011,0.0,0.151,3.219,...,0.0,10.606,275.971,0.0,0.773,0.0,226.070,0.0,0.0,14237000.0
17430,ZWE,Zimbabwe,2018,0.187,5.000,0.0,0.014,0.0,0.187,3.932,...,0.0,12.951,346.284,0.0,0.970,0.0,272.319,0.0,0.0,14439000.0
17431,ZWE,Zimbabwe,2019,0.207,5.020,0.0,0.014,0.0,0.207,3.805,...,0.0,14.112,342.779,0.0,0.956,0.0,259.845,0.0,0.0,14645000.0

#### Getting a part of the dataset to use as 'control' for our transformations

In [4]:
df0.loc[(df0['country'] == 'Brazil') & (df0['year'] == 2018)]

,iso_code,country,year,biofuel_electricity,hydro_electricity,nuclear_electricity,solar_electricity,wind_electricity,other_renewable_electricity,coal_electricity,...,oil_electricity,biofuel_elec_per_capita,hydro_elec_per_capita,nuclear_elec_per_capita,solar_elec_per_capita,wind_elec_per_capita,coal_elec_per_capita,gas_elec_per_capita,oil_elec_per_capita,population
2232,BRA,Brazil,2018,53.911,385.081,15.674,3.461,48.475,53.911,22.241,...,11.422,257.37,1838.368,74.827,16.523,231.419,106.177,245.121,54.529,209468992.0

#### Merging different fuels' columns into one column called 'fuel'

In [5]:
df = df0.melt(id_vars=['iso_code', 'country', 'year', 'population'],
              var_name='fuel',
              value_name='production'
)

df

,iso_code,country,year,population,fuel,production
0,AFG,Afghanistan,1900,5021241.0,biofuel_electricity,NaN
1,AFG,Afghanistan,1901,5053439.0,biofuel_electricity,NaN
2,AFG,Afghanistan,1902,5085403.0,biofuel_electricity,NaN
3,AFG,Afghanistan,1903,5118005.0,biofuel_electricity,NaN
4,AFG,Afghanistan,1904,5150814.0,biofuel_electricity,NaN
...,...,...,...,...,...,...
296339,ZWE,Zimbabwe,2015,13815000.0,oil_elec_per_capita,0.0
296340,ZWE,Zimbabwe,2016,14030000.0,oil_elec_per_capita,0.0
296341,ZWE,Zimbabwe,2017,14237000.0,oil_elec_per_capita,0.0
296342,ZWE,Zimbabwe,2018,14439000.0,oil_elec_per_capita,0.0
296343,ZWE,Zimbabwe,2019,14645000.0,oil_elec_per_capita,0.0

#### Checking the result with our 'control'

In [6]:
df.loc[(df['country'] == 'Brazil') & (df['year'] == 2018)]

,iso_code,country,year,population,fuel,production
2232,BRA,Brazil,2018,209468992.0,biofuel_electricity,53.911
19664,BRA,Brazil,2018,209468992.0,hydro_electricity,385.081
37096,BRA,Brazil,2018,209468992.0,nuclear_electricity,15.674
54528,BRA,Brazil,2018,209468992.0,solar_electricity,3.461
71960,BRA,Brazil,2018,209468992.0,wind_electricity,48.475
89392,BRA,Brazil,2018,209468992.0,other_renewable_electricity,53.911
106824,BRA,Brazil,2018,209468992.0,coal_electricity,22.241
124256,BRA,Brazil,2018,209468992.0,gas_electricity,51.345
141688,BRA,Brazil,2018,209468992.0,oil_electricity,11.422
159120,BRA,Brazil,2018,209468992.0,biofuel_elec_per_capita,257.370
176552,BRA,Brazil,2018,209468992.0,hydro_elec_per_capita,1838.368
193984,BRA,Brazil,2018,209468992.0,nuclear_elec_per_capita,74.827
211416,BRA,Brazil,2018,209468992.0,solar_elec_per_capita,16.523
228848,BRA,Brazil,2018,209468992.0,wind_elec_per_capita,231.419
246280,BRA,Brazil,2018,209468992.0,coal_elec_per_capita,106.177
263712,BRA,Brazil,2018,209468992.0,gas_elec_per_capita,245.121
281144,BRA,Brazil,2018,209468992.0,oil_elec_per_capita,54.529

#### Creating the column 'per_capita' to move the values of fuel_per_capita

In [7]:
#df_pc = df.loc[df['type'].str.contains(r'[a-z]+_per_capita')]
#df_elec = df.loc[df['type'].str.contains(r'[a-z]+_electricity')]

def split_type(row):
    if row['fuel'].find('per_capita') != -1:
        value = row['production']
    else:
        value = 0
    return value

df['per_capita'] = df.apply(split_type, axis=1)

df

,iso_code,country,year,population,fuel,production,per_capita
0,AFG,Afghanistan,1900,5021241.0,biofuel_electricity,NaN,0.0
1,AFG,Afghanistan,1901,5053439.0,biofuel_electricity,NaN,0.0
2,AFG,Afghanistan,1902,5085403.0,biofuel_electricity,NaN,0.0
3,AFG,Afghanistan,1903,5118005.0,biofuel_electricity,NaN,0.0
4,AFG,Afghanistan,1904,5150814.0,biofuel_electricity,NaN,0.0
...,...,...,...,...,...,...,...
296339,ZWE,Zimbabwe,2015,13815000.0,oil_elec_per_capita,0.0,0.0
296340,ZWE,Zimbabwe,2016,14030000.0,oil_elec_per_capita,0.0,0.0
296341,ZWE,Zimbabwe,2017,14237000.0,oil_elec_per_capita,0.0,0.0
296342,ZWE,Zimbabwe,2018,14439000.0,oil_elec_per_capita,0.0,0.0
296343,ZWE,Zimbabwe,2019,14645000.0,oil_elec_per_capita,0.0,0.0

#### Checking it again with our 'control'

In [8]:
df.loc[(df['country'] == 'Brazil') & (df['year'] == 2018)]

,iso_code,country,year,population,fuel,production,per_capita
2232,BRA,Brazil,2018,209468992.0,biofuel_electricity,53.911,0.000
19664,BRA,Brazil,2018,209468992.0,hydro_electricity,385.081,0.000
37096,BRA,Brazil,2018,209468992.0,nuclear_electricity,15.674,0.000
54528,BRA,Brazil,2018,209468992.0,solar_electricity,3.461,0.000
71960,BRA,Brazil,2018,209468992.0,wind_electricity,48.475,0.000
89392,BRA,Brazil,2018,209468992.0,other_renewable_electricity,53.911,0.000
106824,BRA,Brazil,2018,209468992.0,coal_electricity,22.241,0.000
124256,BRA,Brazil,2018,209468992.0,gas_electricity,51.345,0.000
141688,BRA,Brazil,2018,209468992.0,oil_electricity,11.422,0.000
159120,BRA,Brazil,2018,209468992.0,biofuel_elec_per_capita,257.370,257.370
176552,BRA,Brazil,2018,209468992.0,hydro_elec_per_capita,1838.368,1838.368
193984,BRA,Brazil,2018,209468992.0,nuclear_elec_per_capita,74.827,74.827
211416,BRA,Brazil,2018,209468992.0,solar_elec_per_capita,16.523,16.523
228848,BRA,Brazil,2018,209468992.0,wind_elec_per_capita,231.419,231.419
246280,BRA,Brazil,2018,209468992.0,coal_elec_per_capita,106.177,106.177
263712,BRA,Brazil,2018,209468992.0,gas_elec_per_capita,245.121,245.121
281144,BRA,Brazil,2018,209468992.0,oil_elec_per_capita,54.529,54.529

#### Now cleaning the values in column production that were moved to column per_capita

In [9]:
def clean_production(row):
    if row['per_capita'] != 0:
        value = 0
    else:
        value = row['production']
    return value


df['production'] = df.apply(clean_production, axis=1)

df

,iso_code,country,year,population,fuel,production,per_capita
0,AFG,Afghanistan,1900,5021241.0,biofuel_electricity,NaN,0.0
1,AFG,Afghanistan,1901,5053439.0,biofuel_electricity,NaN,0.0
2,AFG,Afghanistan,1902,5085403.0,biofuel_electricity,NaN,0.0
3,AFG,Afghanistan,1903,5118005.0,biofuel_electricity,NaN,0.0
4,AFG,Afghanistan,1904,5150814.0,biofuel_electricity,NaN,0.0
...,...,...,...,...,...,...,...
296339,ZWE,Zimbabwe,2015,13815000.0,oil_elec_per_capita,0.0,0.0
296340,ZWE,Zimbabwe,2016,14030000.0,oil_elec_per_capita,0.0,0.0
296341,ZWE,Zimbabwe,2017,14237000.0,oil_elec_per_capita,0.0,0.0
296342,ZWE,Zimbabwe,2018,14439000.0,oil_elec_per_capita,0.0,0.0
296343,ZWE,Zimbabwe,2019,14645000.0,oil_elec_per_capita,0.0,0.0

#### Again, another check...

In [10]:
df.loc[(df['country'] == 'Brazil') & (df['year'] == 2018)]

,iso_code,country,year,population,fuel,production,per_capita
2232,BRA,Brazil,2018,209468992.0,biofuel_electricity,53.911,0.000
19664,BRA,Brazil,2018,209468992.0,hydro_electricity,385.081,0.000
37096,BRA,Brazil,2018,209468992.0,nuclear_electricity,15.674,0.000
54528,BRA,Brazil,2018,209468992.0,solar_electricity,3.461,0.000
71960,BRA,Brazil,2018,209468992.0,wind_electricity,48.475,0.000
89392,BRA,Brazil,2018,209468992.0,other_renewable_electricity,53.911,0.000
106824,BRA,Brazil,2018,209468992.0,coal_electricity,22.241,0.000
124256,BRA,Brazil,2018,209468992.0,gas_electricity,51.345,0.000
141688,BRA,Brazil,2018,209468992.0,oil_electricity,11.422,0.000
159120,BRA,Brazil,2018,209468992.0,biofuel_elec_per_capita,0.000,257.370
176552,BRA,Brazil,2018,209468992.0,hydro_elec_per_capita,0.000,1838.368
193984,BRA,Brazil,2018,209468992.0,nuclear_elec_per_capita,0.000,74.827
211416,BRA,Brazil,2018,209468992.0,solar_elec_per_capita,0.000,16.523
228848,BRA,Brazil,2018,209468992.0,wind_elec_per_capita,0.000,231.419
246280,BRA,Brazil,2018,209468992.0,coal_elec_per_capita,0.000,106.177
263712,BRA,Brazil,2018,209468992.0,gas_elec_per_capita,0.000,245.121
281144,BRA,Brazil,2018,209468992.0,oil_elec_per_capita,0.000,54.529

#### Cleaning the names in 'fuel'

In [11]:
df['fuel'] = df['fuel'].str.replace('_elec_per_capita', '')
df['fuel'] = df['fuel'].str.replace('_electricity', '')

df['fuel'].unique()

array(['biofuel', 'hydro', 'nuclear', 'solar', 'wind', 'other_renewable',
       'coal', 'gas', 'oil'], dtype=object)

This is just an extra step I realized I need to do to make sure my 'Country' filter would work as intended in the dashboard.

In [12]:
df = df.drop(df[df['country'] == 'World'].index)

df['country'].unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa',
       'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Asia Pacific', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
       'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
       'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'CIS', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Central African Republic', 'Central America',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba',
       'Cyprus', 'Czechia', 'Czechoslovakia',
       'Democratic Republic of Congo', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Eastern Africa', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Europe', 'Europe (other)',
       'Faeroe Islands', 'Falkland Islands ', 'Fiji', 'Finland', 'France',
       'French Guiana', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia',
       'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guadeloupe', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Macau',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Martinique', 'Mauritania', 'Mauritius', 'Mexico', 'Middle Africa',
       'Middle East', 'Moldova', 'Mongolia', 'Montenegro', 'Montserrat',
       'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
       'Netherlands', 'Netherlands Antilles', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'North America', 'North Korea', 'North Macedonia',
       'Northern Mariana Islands', 'Norway', 'OPEC', 'Oman',
       'Other Asia & Pacific', 'Other CIS', 'Other Caribbean',
       'Other Middle East', 'Other Northern Africa',
       'Other South America', 'Other Southern Africa', 'Pakistan',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia',
       'South & Central America', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands',
       'USSR', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'United States Pacific Islands',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Western Africa', 'Western Sahara',
       'Yemen', 'Yugoslavia', 'Zambia', 'Zimbabwe'], dtype=object)

#### Finally, grouping the dataframe and checking the result with our 'control'

In [13]:
df_final = df.groupby(['iso_code', 'country', 'year', 'population', 'fuel']).sum().reset_index()

df_final.loc[(df_final['country'] == 'Brazil') & (df_final['year'] == 2018)]

,iso_code,country,year,population,fuel,production,per_capita
18567,BRA,Brazil,2018,209468992.0,biofuel,53.911,257.370
18568,BRA,Brazil,2018,209468992.0,coal,22.241,106.177
18569,BRA,Brazil,2018,209468992.0,gas,51.345,245.121
18570,BRA,Brazil,2018,209468992.0,hydro,385.081,1838.368
18571,BRA,Brazil,2018,209468992.0,nuclear,15.674,74.827
18572,BRA,Brazil,2018,209468992.0,oil,11.422,54.529
18573,BRA,Brazil,2018,209468992.0,other_renewable,53.911,0.000
18574,BRA,Brazil,2018,209468992.0,solar,3.461,16.523
18575,BRA,Brazil,2018,209468992.0,wind,48.475,231.419

#### Saving it to csv

In [14]:
df_final.to_csv('reworked_dataset.csv',index=False)

#### Now, let's create another dataset to enhance tooltips using a dictionary written manually

In [15]:
description = { 
    'fuel': ['biofuel',
            'coal',
            'gas',
            'hydro',
            'nuclear',
            'oil',
            'other_renewable',
            'solar',
            'wind'],
    'description': ['Any fuel that is derived from biomassâ€”that is, plant or algae material or animal waste. Since such feedstock material can be replenished readily, biofuel is considered to be a source of renewable energy, unlike fossil fuels such as petroleum, coal, and natural gas - Definition by EncyclopÃ¦dia Britannica',
                   'One of the most important primary fossil fuels, a solid carbon-rich material that is usually brown or black and most often occurs in stratified sedimentary deposits. Coal is defined as having more than 50 percent by weight (or 70 percent by volume) carbonaceous matter produced by the compaction and hardening of altered plant remainsâ€”namely, peat deposits - definition by EncyclopÃ¦dia Britannica',
                   'Natural gas, also called methane gas or natural methane gas, colourless highly flammable gaseous hydrocarbon consisting primarily of methane and ethane. It is a type of petroleum that commonly occurs in association with crude oil - Definition by EncyclopÃ¦dia Britannica',
                   'Electricity produced from generators driven by turbines that convert the potential energy of falling or fast-flowing water into mechanical energy - Definition by EncyclopÃ¦dia Britannica',
                   'Electricity generated by power plants that derive their heat from fission in a nuclear reactor. Except for the reactor, which plays the role of a boiler in a fossil-fuel power plant, a nuclear power plant is similar to a large coal-fired power plant, with pumps, valves, steam generators, turbines, electric generators, condensers, and associated equipment - definition by EncyclopÃ¦dia Britannica',
                   'Also called furnace oil, fuel consisting mainly of residues from crude-oil distillation. It is used primarily for steam boilers in power plants, aboard ships, and in industrial plants - Definition by EncyclopÃ¦dia Britannica',
                   'Electricity generated by other forms of renewable energy sources',
                   'Form of renewable energy generated by the conversion of sunlight and artificial light into electricity - Definition by EncyclopÃ¦dia Britannica',
                   'Form of energy conversion in which turbines convert the kinetic energy of wind into mechanical or electrical energy that can be used for power - Definition by EncyclopÃ¦dia Britannica']}

df_desc = pd.DataFrame(description)

df_desc

              fuel                                        description
0          biofuel  Any fuel that is derived from biomassâ€”that i...
1             coal  One of the most important primary fossil fuels...
2              gas  Natural gas, also called methane gas or natura...
3            hydro  Electricity produced from generators driven by...
4          nuclear  Electricity generated by power plants that der...
5              oil  Also called furnace oil, fuel consisting mainl...
6  other_renewable  Electricity generated by other forms of renewa...
7            solar  Form of renewable energy generated by the conv...
8             wind  Form of energy conversion in which turbines co...

#### And saving it to csv

In [16]:
df_desc.to_csv('description_dataset.csv',index=False)

Quite a straightforward process - how it should be. These transformations are quite easy to perform in Pandas but would take a lot of code and workarounds in Tableau for the same result. Now, I can finalize the dashboard with great insights and tooltips!

To see the final dashbaord, please visit [Renewables Energy Dashboard by Pamella](https://public.tableau.com/app/profile/contato/viz/Renewablesenergyanalysis/Dashboard1) in Tableau Public's website.