## 1) RCE Datasset

In [221]:
import pandas as pd


df_mutacao_100_gen = pd.read_excel("/home/pedrov12/Documentos/GitHub/Repopulation-With-Elite-Set/resultados - Artigo PIBIC/resultados_consolidados_variando_mutaca_4x.xlsx")

df_resultados_1 = pd.read_excel("/home/pedrov12/Documentos/GitHub/Repopulation-With-Elite-Set/resultados - Artigo PIBIC/resultados_consolidados_variando_mutaca_4x.xlsx")

display(df_resultados_1.head(2))

,pasta_run,configuracao,execucao,config_num,param_CROSSOVER,param_DELTA_MIN,param_IND_SIZE,param_MUTACAO,param_NUM_GENERATIONS,param_NUM_VAR_DIFERENTES,param_POP_SIZE,param_PORCENTAGEM,param_RCE_REPOPULATION_GENERATIONS,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,best_fitness,best_gen_idx
0,run_2025-08-21_22-49-32,config_1,5,1,0.9,2,5,0.77,100,1,5,0.2,50,16,22,16,16,16,37.354029,99
1,run_2025-08-21_22-49-32,config_1,3,1,0.9,2,5,0.77,100,1,5,0.2,50,23,23,29,29,25,51.160192,99

#### Este DF foi gerado pelo Launcher em output/resultados_consolidados.xlsx

In [222]:

df_resultados_Agosto_Laucher_Streamlit = pd.read_excel("/home/pedrov12/Documentos/GitHub/Repopulation-With-Elite-Set/src/output/resultados_consolidados.xlsx")

In [223]:

best_variables_df = df_resultados_Agosto_Laucher_Streamlit[["best_fitness","best_var_1", "best_var_2", "best_var_3", "best_var_4", "best_var_5","configuracao", "execucao",]]

for i in range(best_variables_df.index.start + 1,best_variables_df.index.stop):
    pass
display(best_variables_df)
(best_variables_df.groupby("configuracao")).mean()

,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,configuracao,execucao
0,38.518904,0,22,0,0,23,config_1,5
1,51.160192,9,10,3,3,11,config_1,3
2,53.023765,12,23,6,6,12,config_1,4
3,54.355180,30,0,23,23,25,config_1,6
4,50.254300,21,6,21,21,17,config_1,2
...,...,...,...,...,...,...,...,...
401,52.257888,6,8,15,15,8,config_1,4
402,66.965104,13,8,22,11,13,config_1,6
403,54.786093,14,22,0,14,23,config_1,2
404,52.331675,29,2,1,1,1,config_1,1
405,54.665122,27,27,6,27,6,config_1,7

,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,execucao
configuracao,,,,,,,
config_1,43.892060,16.587838,14.898649,16.094595,15.918919,17.108108,3.317568
config_2,40.906792,15.655914,14.860215,16.000000,16.172043,16.741935,2.967742
config_3,41.928687,17.529412,13.164706,17.364706,17.541176,16.776471,3.000000
config_4,40.002528,17.475000,12.800000,17.112500,16.937500,17.325000,3.000000

## 2) Limpeza e Tratamento dos resultados consolidados

In [224]:
# --- Fluxo Corrigido ---

# Primeiro, precisamos da função que cria o molde
def renomear_colunas_from_map(df):
  mapa_inicial = {coluna: coluna for coluna in df.columns}
  return mapa_inicial

# 1. Crie o "molde" usando a função correta
mapa_molde = renomear_colunas_from_map(df_resultados_Agosto_Laucher_Streamlit)

# 2. Edite o molde como você já fez (esta parte está perfeita!)
mapa_molde['param_CROSSOVER'] = 'Crossover'
mapa_molde['param_MUTACAO'] = 'Mutação'
mapa_molde['param_NUM_GENERATIONS'] = 'Num_Gerações'
mapa_molde["param_IND_SIZE"] = 'tamanho_individuo'
# ...

# 3. Use o mapa já modificado para renomear, pode ser com o .rename() simples
results_df = df_resultados_Agosto_Laucher_Streamlit.rename(columns=mapa_molde)

# 4. Verifique o resultado
print("\nColunas renomeadas com sucesso!")
results_df.head(3)

Colunas renomeadas com sucesso!

,pasta_run,configuracao,execucao,config_num,Crossover,param_DELTA_MIN,tamanho_individuo,Mutação,Num_Gerações,param_NUM_VAR_DIFERENTES,param_POP_SIZE,param_PORCENTAGEM,param_RCE_REPOPULATION_GENERATIONS,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,best_fitness,best_gen_idx
0,run_2025-08-23_12-19-17,config_1,5,1,0.1,2,5,0.9,20,1,10,0.2,50,0,22,0,0,23,38.518904,19
1,run_2025-08-23_12-19-17,config_1,3,1,0.1,2,5,0.9,20,1,10,0.2,50,9,10,3,3,11,51.160192,19
2,run_2025-08-23_12-19-17,config_1,4,1,0.1,2,5,0.9,20,1,10,0.2,50,12,23,6,6,12,53.023765,19

In [225]:
def aplicar_renomeacao(df, mapa_de_nomes, manter_apenas_mapeadas=False):
  """
  Renomeia colunas de um DataFrame e, opcionalmente, mantém apenas as
  colunas que foram especificadas no mapa de renomeação.

  Args:
    df (pd.DataFrame): O DataFrame original.
    mapa_de_nomes (dict): Dicionário com {nome_antigo: nome_novo}.
    manter_apenas_mapeadas (bool): Se True, descarta todas as outras colunas.
  
  Returns:
    pd.DataFrame: O DataFrame transformado.
  """
  # Primeiro, renomeia as colunas normalmente
  df_renomeado = df.rename(columns=mapa_de_nomes)

  # Agora, a nova lógica que você sugeriu:
  if manter_apenas_mapeadas:
    # Pega a lista dos novos nomes de coluna (os valores do dicionário)
    colunas_para_manter = list(mapa_de_nomes.values())
    
    # Retorna o DataFrame contendo APENAS essas colunas
    return df_renomeado[colunas_para_manter]
  else:
    # Se for False, retorna o DataFrame com todas as colunas (com os nomes trocados)
    return df_renomeado

# --- Como usar ---

# 1. Crie um mapa APENAS com as colunas que te interessam
mapa_essencial = {
      "pasta_run":"pasta_run",
    'config_num':"Número Config",
    'param_CROSSOVER': 'Crossover', # Pode mapear para o mesmo nome
    'param_MUTACAO': 'Mutação',
    'param_NUM_GENERATIONS': 'Número de Gerações',
    'param_POP_SIZE': "Tamanho População",
    "param_IND_SIZE": "Tamanho Individuo",
    "best_gen_idx": "Melhor Geração",
    "best_fitness": "best_fitness",
    
}


# Use o DataFrame que já tinha alguns nomes trocados, o df_novo
# Caso de uso 1: Apenas renomear 'melhor_fitness' para 'fitness_final'
df_alterado = aplicar_renomeacao(df_resultados_Agosto_Laucher_Streamlit, mapa_essencial,True)

print("--- Rodando com manter_apenas_mapeadas=True ---")
display(df_alterado.head())


print("Resultados gerais para cada configuração executada")
#df_resultado = pd.merge(df_alterado, best_variables_df, on='best_fitness')
df_resultado = pd.concat([df_alterado, best_variables_df], axis=1)
df_resultado

--- Rodando com manter_apenas_mapeadas=True ---

,pasta_run,Número Config,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração,best_fitness
0,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,38.518904
1,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,51.160192
2,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,53.023765
3,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,54.355180
4,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,50.254300

Resultados gerais para cada configuração executada

,pasta_run,Número Config,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração,best_fitness,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,configuracao,execucao
0,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,38.518904,38.518904,0,22,0,0,23,config_1,5
1,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,51.160192,51.160192,9,10,3,3,11,config_1,3
2,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,53.023765,53.023765,12,23,6,6,12,config_1,4
3,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,54.355180,54.355180,30,0,23,23,25,config_1,6
4,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,50.254300,50.254300,21,6,21,21,17,config_1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,run_2025-08-23_11-54-33,1,0.1,0.9,20,10,5,19,52.257888,52.257888,6,8,15,15,8,config_1,4
402,run_2025-08-23_11-54-33,1,0.1,0.9,20,10,5,19,66.965104,66.965104,13,8,22,11,13,config_1,6
403,run_2025-08-23_11-54-33,1,0.1,0.9,20,10,5,19,54.786093,54.786093,14,22,0,14,23,config_1,2
404,run_2025-08-23_11-54-33,1,0.1,0.9,20,10,5,19,52.331675,52.331675,29,2,1,1,1,config_1,1
405,run_2025-08-23_11-54-33,1,0.1,0.9,20,10,5,19,54.665122,54.665122,27,27,6,27,6,config_1,7

## Tratamento para o tempo de execução

In [226]:
import pandas as pd

def validate_time_laucher(df):
    """
    Calcula o tempo médio de execução para cada configuração por dia.

    A função executa os seguintes passos:
    1. Converte a coluna 'pasta_run' para um formato de data/hora.
    2. Cria uma coluna 'data' para agrupar as execuções por dia.
    3. Agrupa os dados por 'data' e 'configuracao'.
    4. Calcula a duração total das execuções para cada grupo.
    5. Conta o número de execuções em cada grupo.
    6. Calcula o tempo médio de execução e o adiciona como uma nova coluna.

    Args:
      df (pd.DataFrame): O DataFrame original contendo a coluna 'pasta_run'.

    Returns:
      pd.DataFrame: O DataFrame com as novas colunas de tempo e data.
    """
    df_calculado = df.copy()

    # Passo 1: Limpar a string e converter para datetime
    timestamp_str = df_calculado['pasta_run'].str.replace('run_', '')
    df_calculado['timestamp'] = pd.to_datetime(timestamp_str, format='%Y-%m-%d_%H-%M-%S')

    # Passo 2: Extrair a data para uma nova coluna
    df_calculado['data'] = df_calculado['timestamp'].dt.date

    # Passo 3, 4 e 5: Agrupar e calcular duração e contagem
    grupos = ['data', 'configuracao']
    tempo_min_grupo = df_calculado.groupby(grupos)['timestamp'].transform('min')
    tempo_max_grupo = df_calculado.groupby(grupos)['timestamp'].transform('max')
    duracao_total = tempo_max_grupo - tempo_min_grupo
    num_execucoes = df_calculado.groupby(grupos)['execucao'].transform('count')

    # Passo 6: Calcular o tempo médio
    df_calculado['tempo_medio_execucao'] = duracao_total / num_execucoes

    return df_calculado
#na coluna hora vc tem que fazer todos os horarios do dia um hora pela outra para saber o tempo de execucao de cada config e dividir pelo número de execuções e uma coluna data para saber o dia

df_resultado[["pasta_run"]].value_counts()


df_time = validate_time_laucher(df_resultado)
df_time

,pasta_run,Número Config,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração,best_fitness,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,configuracao,execucao,timestamp,data,tempo_medio_execucao
0,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,38.518904,38.518904,0,22,0,0,23,config_1,5,2025-08-23 12:19:17,2025-08-23,0 days 00:08:25
1,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,51.160192,51.160192,9,10,3,3,11,config_1,3,2025-08-23 12:19:17,2025-08-23,0 days 00:08:25
2,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,53.023765,53.023765,12,23,6,6,12,config_1,4,2025-08-23 12:19:17,2025-08-23,0 days 00:08:25
3,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,54.355180,54.355180,30,0,23,23,25,config_1,6,2025-08-23 12:19:17,2025-08-23,0 days 00:08:25
4,run_2025-08-23_12-19-17,1,0.1,0.9,20,10,5,19,50.254300,50.254300,21,6,21,21,17,config_1,2,2025-08-23 12:19:17,2025-08-23,0 days 00:08:25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,run_2025-08-23_11-54-33,1,0.1,0.9,20,10,5,19,52.257888,52.257888,6,8,15,15,8,config_1,4,2025-08-23 11:54:33,2025-08-23,0 days 00:08:25
402,run_2025-08-23_11-54-33,1,0.1,0.9,20,10,5,19,66.965104,66.965104,13,8,22,11,13,config_1,6,2025-08-23 11:54:33,2025-08-23,0 days 00:08:25
403,run_2025-08-23_11-54-33,1,0.1,0.9,20,10,5,19,54.786093,54.786093,14,22,0,14,23,config_1,2,2025-08-23 11:54:33,2025-08-23,0 days 00:08:25
404,run_2025-08-23_11-54-33,1,0.1,0.9,20,10,5,19,52.331675,52.331675,29,2,1,1,1,config_1,1,2025-08-23 11:54:33,2025-08-23,0 days 00:08:25
405,run_2025-08-23_11-54-33,1,0.1,0.9,20,10,5,19,54.665122,54.665122,27,27,6,27,6,config_1,7,2025-08-23 11:54:33,2025-08-23,0 days 00:08:25

In [227]:
import pandas as pd

def calcula_tempo_execucao(df):
    """
    Calcula o tempo médio de execução para cada grupo de configuração
    e adiciona como uma nova coluna no DataFrame.
    """
    # É uma boa prática trabalhar com uma cópia para não modificar o df original inesperadamente
    df_calculado = df.copy()

    # 1. Converte a coluna 'pasta_run' para um formato de data e hora (timestamp)
    # Primeiro removemos o "run_" do início do texto
    df_calculado['timestamp'] = df_calculado['pasta_run'].str.replace('run_', '')
    # Agora convertemos o texto restante para data/hora
    df_calculado['timestamp'] = pd.to_datetime(df_calculado['timestamp'], format='%Y-%m-%d_%H-%M-%S')

    # 2. Para cada grupo 'configuracao', calcula a duração total
    # A função .transform() é ótima aqui, pois ela realiza o cálculo por grupo
    # mas retorna um resultado com o mesmo tamanho do DataFrame original.
    tempo_min_grupo = df_calculado.groupby('configuracao')['timestamp'].transform('min')
    tempo_max_grupo = df_calculado.groupby('configuracao')['timestamp'].transform('max')

    duracao_total = tempo_max_grupo - tempo_min_grupo

    # 3. Conta o número de execuções em cada grupo
    num_execucoes = df_calculado.groupby('configuracao')['execucao'].transform('count')

    # 4. Calcula o tempo médio e cria a nova coluna
    # Verificamos se num_execucoes > 0 para evitar divisão por zero
    if not num_execucoes.empty:
      df_calculado['tempo_medio_execucao'] = duracao_total / num_execucoes
    else:
      df_calculado['tempo_medio_execucao'] = pd.NaT # preenche com nulo se não houver execuções

    return df_calculado

In [228]:


# --- Como usar tudo junto ---

# 1. Renomeie o DataFrame original
df_novo = df_resultado.rename(columns=mapa_molde)

# 2. Passe o DataFrame renomeado para a sua nova função
df_final = calcula_tempo_execucao(df_novo)

# 3. Veja o resultado!
# Usamos o .head() para ver as primeiras linhas e as novas colunas
print("\nDataFrame final com a coluna de tempo médio:")
display(df_final[['configuracao', 'execucao','timestamp', 'tempo_medio_execucao']].head())


# Supondo que seu DataFrame se chame 'df_final' e a coluna 'tempo_medio_execucao'
formatar_tempo = lambda td: f"{int(td.total_seconds() // 3600):02d}:{int((td.total_seconds() % 3600) // 60):02d}:{int(td.total_seconds() % 60):02d}"

# 2. Aplicamos essa função na coluna e criamos uma nova coluna formatada
df_final['tempo_formatado'] = df_final['tempo_medio_execucao'].apply(formatar_tempo)

# 3. Vamos ver o resultado
print("Coluna original vs. Coluna formatada:")
display(df_final[['tempo_medio_execucao', 'tempo_formatado']].head())


print("DF Resultados Final")
df_final = df_final.dropna()
df_final = df_final.drop(
  columns=['pasta_run', 'tempo_medio_execucao', 'timestamp']
)

print("Resultados Finais tratados para o Dashboard")
df_final.to_excel("/home/pedrov12/Documentos/GitHub/Repopulation-With-Elite-Set/src/output/resultados.xlsx", index=False)

df_final

DataFrame final com a coluna de tempo médio:

  configuracao  execucao           timestamp      tempo_medio_execucao
0     config_1         5 2025-08-23 12:19:17 0 days 00:15:27.594594594
1     config_1         3 2025-08-23 12:19:17 0 days 00:15:27.594594594
2     config_1         4 2025-08-23 12:19:17 0 days 00:15:27.594594594
3     config_1         6 2025-08-23 12:19:17 0 days 00:15:27.594594594
4     config_1         2 2025-08-23 12:19:17 0 days 00:15:27.594594594

Coluna original vs. Coluna formatada:

       tempo_medio_execucao tempo_formatado
0 0 days 00:15:27.594594594        00:15:27
1 0 days 00:15:27.594594594        00:15:27
2 0 days 00:15:27.594594594        00:15:27
3 0 days 00:15:27.594594594        00:15:27
4 0 days 00:15:27.594594594        00:15:27

DF Resultados Final
Resultados Finais tratados para o Dashboard

,Número Config,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração,best_fitness,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,configuracao,execucao,tempo_formatado
0,1,0.1,0.9,20,10,5,19,38.518904,38.518904,0,22,0,0,23,config_1,5,00:15:27
1,1,0.1,0.9,20,10,5,19,51.160192,51.160192,9,10,3,3,11,config_1,3,00:15:27
2,1,0.1,0.9,20,10,5,19,53.023765,53.023765,12,23,6,6,12,config_1,4,00:15:27
3,1,0.1,0.9,20,10,5,19,54.355180,54.355180,30,0,23,23,25,config_1,6,00:15:27
4,1,0.1,0.9,20,10,5,19,50.254300,50.254300,21,6,21,21,17,config_1,2,00:15:27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,1,0.1,0.9,20,10,5,19,52.257888,52.257888,6,8,15,15,8,config_1,4,00:15:27
402,1,0.1,0.9,20,10,5,19,66.965104,66.965104,13,8,22,11,13,config_1,6,00:15:27
403,1,0.1,0.9,20,10,5,19,54.786093,54.786093,14,22,0,14,23,config_1,2,00:15:27
404,1,0.1,0.9,20,10,5,19,52.331675,52.331675,29,2,1,1,1,config_1,1,00:15:27
405,1,0.1,0.9,20,10,5,19,54.665122,54.665122,27,27,6,27,6,config_1,7,00:15:27

## 3) Criação de tabelas e fazer seus UML com Diagrama de Classes com o uso do software

In [229]:

# tabela RCE


# Tabela AG-DEAP


# Tabela_Solutions

In [230]:
def separar_em_tabelas(df, coluna_criterio):
  """
  Separa um DataFrame em um dicionário de DataFrames menores,
  baseado nos valores únicos de uma coluna.

  Args:
    df (pd.DataFrame): O DataFrame a ser separado.
    coluna_criterio (str): O nome da coluna usada para agrupar.

  Returns:
    dict: Um dicionário onde as chaves são os valores da coluna
          e os valores são os DataFrames correspondentes.
  """
  tabelas_separadas = {}
  
  # O .groupby() cria um objeto que podemos percorrer com um loop.
  # Em cada passo, ele nos dá o nome do grupo e o DataFrame daquele grupo.
  for nome_do_grupo, df_do_grupo in df.groupby(coluna_criterio):
    # Usamos o nome do grupo como a chave do nosso dicionário
    # e guardamos o DataFrame correspondente como o valor.
    tabelas_separadas[nome_do_grupo] = df_do_grupo.copy() # .copy() evita avisos do pandas
  
  return tabelas_separadas

# --- Como usar a função ---

# Vamos usar seu DataFrame final e separá-lo por 'configuracao'
dicionario_de_tabelas = separar_em_tabelas(df_resultados_Agosto_Laucher_Streamlit, 'configuracao')

# Agora, 'dicionario_de_tabelas' contém todas as suas tabelas separadas.
print("Tabelas criadas:", list(dicionario_de_tabelas.keys()))

df_config_1 = dicionario_de_tabelas['config_1']


print("\nCabeçalho da tabela apenas para 'config_1':")
display(df_config_1.head())

Tabelas criadas: ['config_1', 'config_2', 'config_3', 'config_4']

Cabeçalho da tabela apenas para 'config_1':

,pasta_run,configuracao,execucao,config_num,param_CROSSOVER,param_DELTA_MIN,param_IND_SIZE,param_MUTACAO,param_NUM_GENERATIONS,param_NUM_VAR_DIFERENTES,param_POP_SIZE,param_PORCENTAGEM,param_RCE_REPOPULATION_GENERATIONS,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,best_fitness,best_gen_idx
0,run_2025-08-23_12-19-17,config_1,5,1,0.1,2,5,0.9,20,1,10,0.2,50,0,22,0,0,23,38.518904,19
1,run_2025-08-23_12-19-17,config_1,3,1,0.1,2,5,0.9,20,1,10,0.2,50,9,10,3,3,11,51.160192,19
2,run_2025-08-23_12-19-17,config_1,4,1,0.1,2,5,0.9,20,1,10,0.2,50,12,23,6,6,12,53.023765,19
3,run_2025-08-23_12-19-17,config_1,6,1,0.1,2,5,0.9,20,1,10,0.2,50,30,0,23,23,25,54.355180,19
4,run_2025-08-23_12-19-17,config_1,2,1,0.1,2,5,0.9,20,1,10,0.2,50,21,6,21,21,17,50.254300,19

## 3) Análisando os parametros AG

In [243]:
def display_value_counts(df, column_name):
    return df[column_name].value_counts()


print("Total de execuções pelo Laucher.py", df_final.shape[0])
print("Colunas do DataFrame",df_final.columns)

display(display_value_counts(df_final, 'Crossover'))
display(display_value_counts(df_final, 'Mutação'))
display(display_value_counts(df_final, 'Número de Gerações'))
display(display_value_counts(df_final, 'Tamanho População'))
display(display_value_counts(df_final, 'Melhor Geração'))

Total de execuções pelo Laucher.py 406
Colunas do DataFrame Index(['Número Config', 'Crossover', 'Mutação', 'Número de Gerações',
       'Tamanho População', 'Tamanho Individuo', 'Melhor Geração',
       'best_fitness', 'best_fitness', 'best_var_1', 'best_var_2',
       'best_var_3', 'best_var_4', 'best_var_5', 'configuracao', 'execucao',
       'tempo_formatado'],
      dtype='object')

Crossover
0.9    129
0.8     78
0.7     75
0.6     75
0.1     49
Name: count, dtype: int64

Mutação
0.90     362
0.77      19
0.50      10
90.00     10
0.25       5
Name: count, dtype: int64

Número de Gerações
100    347
20      49
5       10
Name: count, dtype: int64

Tamanho População
10    357
5      49
Name: count, dtype: int64

Melhor Geração
99    347
19     49
4      10
Name: count, dtype: int64

## 4) Análisando os parametros RCE

## 4 fitness functions

## Config params.json to 20x executions

## Simulate Pandapower network