## Notebook Data Analysis para o RCE Framework Laucher usando Função objetivo - IEEE 14
---

## 1) RCE Datasset

In [28]:
import pandas as pd


df_mutacao_100_gen = pd.read_excel("/home/pedrov12/Documentos/GitHub/Repopulation-With-Elite-Set/resultados - Artigo PIBIC/dataset/resultados_consolidados_variando_mutaca_4x.xlsx")

df_resultados_4x_mutacao = pd.read_excel("/home/pedrov12/Documentos/GitHub/Repopulation-With-Elite-Set/resultados - Artigo PIBIC/dataset/resultados_consolidados_variando_mutaca_4x.xlsx")

df_resultados_Agosto_Laucher_Streamlit = pd.read_excel("/home/pedrov12/Documentos/GitHub/Repopulation-With-Elite-Set/src/output/resultados_consolidados.xlsx")

#### Este DF foi gerado pelo Launcher em output/resultados_consolidados.xlsx

In [29]:


df_resultados_Agosto_Laucher_Streamlit.head(3)

,pasta_run,configuracao,execucao,config_num,param_CROSSOVER,param_DELTA_MIN,param_IND_SIZE,param_MUTACAO,param_NUM_GENERATIONS,param_NUM_VAR_DIFERENTES,...,best_var_2,best_var_3,best_var_4,best_var_5,best_var_6,best_var_7,best_var_8,best_var_9,best_fitness,best_gen_idx
0,run_2025-08-25_20-39-32,config_1,1,1,0.1,2,5,0.15,20,1,...,23,23,23,4,NaN,NaN,NaN,NaN,52.659393,19
1,run_2025-08-25_20-39-32,config_1,2,1,0.1,2,5,0.15,20,1,...,4,21,21,4,NaN,NaN,NaN,NaN,53.520267,19
2,run_2025-08-25_20-39-32,config_1,3,1,0.1,2,5,0.15,20,1,...,21,14,7,14,NaN,NaN,NaN,NaN,56.019151,19

In [30]:

best_variables_df = df_resultados_Agosto_Laucher_Streamlit[["best_fitness","best_var_1", "best_var_2", "best_var_3", "best_var_4", "best_var_5", "best_var_6", "best_var_7", "best_var_8", "best_var_9", "configuracao", "execucao",]]

for i in range(best_variables_df.index.start + 1,best_variables_df.index.stop):
    pass
display(best_variables_df)
(best_variables_df.groupby("configuracao")).mean()

,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,best_var_6,best_var_7,best_var_8,best_var_9,configuracao,execucao
0,52.659393,2,23,23,23,4,NaN,NaN,NaN,NaN,config_1,1
1,53.520267,30,4,21,21,4,NaN,NaN,NaN,NaN,config_1,2
2,56.019151,7,21,14,7,14,NaN,NaN,NaN,NaN,config_1,3
3,75.618946,26,27,28,2,28,NaN,NaN,NaN,NaN,config_1,4
4,83.777181,31,22,7,7,27,NaN,NaN,NaN,NaN,config_2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
238,73.000000,1,5,3,1,4,0.0,1.0,4.0,0.0,config_4,3
239,528.000000,5,6,15,0,5,4.0,4.0,11.0,0.0,config_4,4
240,64.013561,17,0,17,5,1,0.0,17.0,0.0,11.0,config_1,1
241,70.031222,9,27,11,15,11,27.0,11.0,0.0,23.0,config_1,1
242,62.273992,3,3,3,12,9,28.0,12.0,3.0,9.0,config_1,2

,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,best_var_6,best_var_7,best_var_8,best_var_9,execucao
configuracao,,,,,,,,,,,
config_1,111.872677,12.952381,14.158730,15.619048,12.460317,11.873016,17.657143,14.742857,14.0000,7.971429,2.444444
config_2,99.199837,16.016667,14.383333,14.050000,15.333333,14.450000,14.187500,12.000000,14.1250,10.593750,2.500000
config_3,43.000864,14.400000,13.816667,14.583333,12.233333,14.700000,12.281250,11.156250,16.5000,13.406250,2.500000
config_4,46.898883,15.716667,14.283333,14.016667,17.333333,14.516667,12.312500,14.062500,14.9375,13.187500,2.500000

## 2) Limpeza e Tratamento dos resultados consolidados

In [31]:
# --- Fluxo Corrigido ---

# Primeiro, precisamos da função que cria o molde
def renomear_colunas_from_map(df):
  mapa_inicial = {coluna: coluna for coluna in df.columns}
  return mapa_inicial

# 1. Crie o "molde" usando a função correta
mapa_molde = renomear_colunas_from_map(df_resultados_Agosto_Laucher_Streamlit)

# 2. Edite o molde como você já fez (esta parte está perfeita!)
mapa_molde['param_CROSSOVER'] = 'Crossover'
mapa_molde['param_MUTACAO'] = 'Mutação'
mapa_molde['param_NUM_GENERATIONS'] = 'Num_Gerações'
mapa_molde["param_IND_SIZE"] = 'tamanho_individuo'
# ...

# 3. Use o mapa já modificado para renomear, pode ser com o .rename() simples
results_df = df_resultados_Agosto_Laucher_Streamlit.rename(columns=mapa_molde)

# 4. Verifique o resultado
print("\nColunas renomeadas com sucesso!")
results_df.head(3)

Colunas renomeadas com sucesso!

,pasta_run,configuracao,execucao,config_num,Crossover,param_DELTA_MIN,tamanho_individuo,Mutação,Num_Gerações,param_NUM_VAR_DIFERENTES,...,best_var_2,best_var_3,best_var_4,best_var_5,best_var_6,best_var_7,best_var_8,best_var_9,best_fitness,best_gen_idx
0,run_2025-08-25_20-39-32,config_1,1,1,0.1,2,5,0.15,20,1,...,23,23,23,4,NaN,NaN,NaN,NaN,52.659393,19
1,run_2025-08-25_20-39-32,config_1,2,1,0.1,2,5,0.15,20,1,...,4,21,21,4,NaN,NaN,NaN,NaN,53.520267,19
2,run_2025-08-25_20-39-32,config_1,3,1,0.1,2,5,0.15,20,1,...,21,14,7,14,NaN,NaN,NaN,NaN,56.019151,19

In [32]:
def aplicar_renomeacao(df, mapa_de_nomes, manter_apenas_mapeadas=False):
  """
  Renomeia colunas de um DataFrame e, opcionalmente, mantém apenas as
  colunas que foram especificadas no mapa de renomeação.

  Args:
    df (pd.DataFrame): O DataFrame original.
    mapa_de_nomes (dict): Dicionário com {nome_antigo: nome_novo}.
    manter_apenas_mapeadas (bool): Se True, descarta todas as outras colunas.
  
  Returns:
    pd.DataFrame: O DataFrame transformado.
  """
  # Primeiro, renomeia as colunas normalmente
  df_renomeado = df.rename(columns=mapa_de_nomes)

  # Agora, a nova lógica que você sugeriu:
  if manter_apenas_mapeadas:
    # Pega a lista dos novos nomes de coluna (os valores do dicionário)
    colunas_para_manter = list(mapa_de_nomes.values())
    
    # Retorna o DataFrame contendo APENAS essas colunas
    return df_renomeado[colunas_para_manter]
  else:
    # Se for False, retorna o DataFrame com todas as colunas (com os nomes trocados)
    return df_renomeado

# --- Como usar ---

# 1. Crie um mapa APENAS com as colunas que te interessam
mapa_essencial = {
      "pasta_run":"pasta_run",
    'config_num':"Número Config",
    'param_CROSSOVER': 'Crossover', # Pode mapear para o mesmo nome
    'param_MUTACAO': 'Mutação',
    'param_NUM_GENERATIONS': 'Número de Gerações',
    'param_POP_SIZE': "Tamanho População",
    "param_IND_SIZE": "Tamanho Individuo",
    "best_gen_idx": "Melhor Geração",
    
}


# Use o DataFrame que já tinha alguns nomes trocados, o df_novo
# Caso de uso 1: Apenas renomear 'melhor_fitness' para 'fitness_final'
df_alterado = aplicar_renomeacao(df_resultados_Agosto_Laucher_Streamlit, mapa_essencial,True)

print("--- Rodando com manter_apenas_mapeadas=True ---")
display(df_alterado.head())


print("Resultados gerais para cada configuração executada")
#df_resultado = pd.merge(df_alterado, best_variables_df, on='best_fitness')
df_resultado = pd.concat([df_alterado, best_variables_df], axis=1)
df_resultado

--- Rodando com manter_apenas_mapeadas=True ---

,pasta_run,Número Config,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração
0,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19
1,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19
2,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19
3,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19
4,run_2025-08-25_20-39-32,2,0.9,0.15,20,5,5,19

Resultados gerais para cada configuração executada

,pasta_run,Número Config,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,best_var_6,best_var_7,best_var_8,best_var_9,configuracao,execucao
0,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19,52.659393,2,23,23,23,4,NaN,NaN,NaN,NaN,config_1,1
1,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19,53.520267,30,4,21,21,4,NaN,NaN,NaN,NaN,config_1,2
2,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19,56.019151,7,21,14,7,14,NaN,NaN,NaN,NaN,config_1,3
3,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19,75.618946,26,27,28,2,28,NaN,NaN,NaN,NaN,config_1,4
4,run_2025-08-25_20-39-32,2,0.9,0.15,20,5,5,19,83.777181,31,22,7,7,27,NaN,NaN,NaN,NaN,config_2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,run_2025-08-26_21-49-56,4,0.1,0.90,50,5,10,49,73.000000,1,5,3,1,4,0.0,1.0,4.0,0.0,config_4,3
239,run_2025-08-26_21-49-56,4,0.1,0.90,50,5,10,49,528.000000,5,6,15,0,5,4.0,4.0,11.0,0.0,config_4,4
240,run_2025-08-26_22-50-33,1,0.1,0.90,20,10,10,16,64.013561,17,0,17,5,1,0.0,17.0,0.0,11.0,config_1,1
241,run_2025-08-26_23-01-40,1,0.5,0.90,20,10,10,6,70.031222,9,27,11,15,11,27.0,11.0,0.0,23.0,config_1,1
242,run_2025-08-26_23-01-40,1,0.5,0.90,20,10,10,19,62.273992,3,3,3,12,9,28.0,12.0,3.0,9.0,config_1,2

## Tratamento para o tempo de execução

In [33]:
import pandas as pd

def validate_time_laucher(df):
    """
    Calcula o tempo médio de execução para cada configuração por dia.

    A função executa os seguintes passos:
    1. Converte a coluna 'pasta_run' para um formato de data/hora.
    2. Cria uma coluna 'data' para agrupar as execuções por dia.
    3. Agrupa os dados por 'data' e 'configuracao'.
    4. Calcula a duração total das execuções para cada grupo.
    5. Conta o número de execuções em cada grupo.
    6. Calcula o tempo médio de execução e o adiciona como uma nova coluna.

    Args:
      df (pd.DataFrame): O DataFrame original contendo a coluna 'pasta_run'.

    Returns:
      pd.DataFrame: O DataFrame com as novas colunas de tempo e data.
    """
    df_calculado = df.copy()

    # Passo 1: Limpar a string e converter para datetime
    timestamp_str = df_calculado['pasta_run'].str.replace('run_', '')
    df_calculado['timestamp'] = pd.to_datetime(timestamp_str, format='%Y-%m-%d_%H-%M-%S')

    # Passo 2: Extrair a data para uma nova coluna
    df_calculado['data'] = df_calculado['timestamp'].dt.date

    # Passo 3, 4 e 5: Agrupar e calcular duração e contagem
    grupos = ['data', 'configuracao']
    tempo_min_grupo = df_calculado.groupby(grupos)['timestamp'].transform('min')
    tempo_max_grupo = df_calculado.groupby(grupos)['timestamp'].transform('max')
    duracao_total = tempo_max_grupo - tempo_min_grupo
    num_execucoes = df_calculado.groupby(grupos)['execucao'].transform('count')

    # Passo 6: Calcular o tempo médio
    df_calculado['tempo_medio_execucao'] = duracao_total / num_execucoes

    return df_calculado
#na coluna hora vc tem que fazer todos os horarios do dia um hora pela outra para saber o tempo de execucao de cada config e dividir pelo número de execuções e uma coluna data para saber o dia

df_resultado[["pasta_run"]].value_counts()


df_time = validate_time_laucher(df_resultado)
df_time

,pasta_run,Número Config,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração,best_fitness,best_var_1,...,best_var_5,best_var_6,best_var_7,best_var_8,best_var_9,configuracao,execucao,timestamp,data,tempo_medio_execucao
0,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19,52.659393,2,...,4,NaN,NaN,NaN,NaN,config_1,1,2025-08-25 20:39:32,2025-08-25,0 days 00:02:22.500000
1,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19,53.520267,30,...,4,NaN,NaN,NaN,NaN,config_1,2,2025-08-25 20:39:32,2025-08-25,0 days 00:02:22.500000
2,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19,56.019151,7,...,14,NaN,NaN,NaN,NaN,config_1,3,2025-08-25 20:39:32,2025-08-25,0 days 00:02:22.500000
3,run_2025-08-25_20-39-32,1,0.1,0.15,20,5,5,19,75.618946,26,...,28,NaN,NaN,NaN,NaN,config_1,4,2025-08-25 20:39:32,2025-08-25,0 days 00:02:22.500000
4,run_2025-08-25_20-39-32,2,0.9,0.15,20,5,5,19,83.777181,31,...,27,NaN,NaN,NaN,NaN,config_2,1,2025-08-25 20:39:32,2025-08-25,0 days 00:02:22.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,run_2025-08-26_21-49-56,4,0.1,0.90,50,5,10,49,73.000000,1,...,4,0.0,1.0,4.0,0.0,config_4,3,2025-08-26 21:49:56,2025-08-26,0 days 00:15:50.125000
239,run_2025-08-26_21-49-56,4,0.1,0.90,50,5,10,49,528.000000,5,...,5,4.0,4.0,11.0,0.0,config_4,4,2025-08-26 21:49:56,2025-08-26,0 days 00:15:50.125000
240,run_2025-08-26_22-50-33,1,0.1,0.90,20,10,10,16,64.013561,17,...,1,0.0,17.0,0.0,11.0,config_1,1,2025-08-26 22:50:33,2025-08-26,0 days 00:16:31.657142857
241,run_2025-08-26_23-01-40,1,0.5,0.90,20,10,10,6,70.031222,9,...,11,27.0,11.0,0.0,23.0,config_1,1,2025-08-26 23:01:40,2025-08-26,0 days 00:16:31.657142857
242,run_2025-08-26_23-01-40,1,0.5,0.90,20,10,10,19,62.273992,3,...,9,28.0,12.0,3.0,9.0,config_1,2,2025-08-26 23:01:40,2025-08-26,0 days 00:16:31.657142857

In [34]:
import pandas as pd

def calcula_tempo_execucao(df):
    """
    Calcula o tempo médio de execução para cada grupo de configuração
    e adiciona como uma nova coluna no DataFrame.
    """
    # É uma boa prática trabalhar com uma cópia para não modificar o df original inesperadamente
    df_calculado = df.copy()

    # 1. Converte a coluna 'pasta_run' para um formato de data e hora (timestamp)
    # Primeiro removemos o "run_" do início do texto
    df_calculado['timestamp'] = df_calculado['pasta_run'].str.replace('run_', '')
    # Agora convertemos o texto restante para data/hora
    df_calculado['timestamp'] = pd.to_datetime(df_calculado['timestamp'], format='%Y-%m-%d_%H-%M-%S')

    # 2. Para cada grupo 'configuracao', calcula a duração total
    # A função .transform() é ótima aqui, pois ela realiza o cálculo por grupo
    # mas retorna um resultado com o mesmo tamanho do DataFrame original.
    tempo_min_grupo = df_calculado.groupby('configuracao')['timestamp'].transform('min')
    tempo_max_grupo = df_calculado.groupby('configuracao')['timestamp'].transform('max')

    duracao_total = tempo_max_grupo - tempo_min_grupo

    # 3. Conta o número de execuções em cada grupo
    num_execucoes = df_calculado.groupby('configuracao')['execucao'].transform('count')

    # 4. Calcula o tempo médio e cria a nova coluna
    # Verificamos se num_execucoes > 0 para evitar divisão por zero
    if not num_execucoes.empty:
      df_calculado['tempo_medio_execucao'] = duracao_total / num_execucoes
    else:
      df_calculado['tempo_medio_execucao'] = pd.NaT # preenche com nulo se não houver execuções

    return df_calculado

In [35]:


# --- Como usar tudo junto ---

# 1. Renomeie o DataFrame original
df_novo = df_resultado.rename(columns=mapa_molde)

# 2. Passe o DataFrame renomeado para a sua nova função
df_final = calcula_tempo_execucao(df_novo)

# 3. Veja o resultado!
# Usamos o .head() para ver as primeiras linhas e as novas colunas
print("\nDataFrame final com a coluna de tempo médio:")
display(df_final[['configuracao', 'execucao','timestamp', 'tempo_medio_execucao']].head())


# Supondo que seu DataFrame se chame 'df_final' e a coluna 'tempo_medio_execucao'
formatar_tempo = lambda td: f"{int(td.total_seconds() // 3600):02d}:{int((td.total_seconds() % 3600) // 60):02d}:{int(td.total_seconds() % 60):02d}"

# 2. Aplicamos essa função na coluna e criamos uma nova coluna formatada
df_final['tempo_formatado'] = df_final['tempo_medio_execucao'].apply(formatar_tempo)

# 3. Vamos ver o resultado
print("Coluna original vs. Coluna formatada:")
display(df_final[['tempo_medio_execucao', 'tempo_formatado']].head())

# A lambda pega o tempo (td), calcula o total de segundos,
# e formata em minutos (:02d) e segundos (:02d)
formatar_min_sec = lambda td: f"{int(td.total_seconds() // 60):02d}:{int(td.total_seconds() % 60):02d}"


#df_final['tempo_min_sec'] = df_final['tempo_medio_execucao'].apply(formatar_min_sec)

#print("Coluna original vs. Coluna formatada (MM:SS):")
#display(df_final[['tempo_medio_execucao', 'tempo_min_sec']].head())


print("DF Resultados Final")
df_final = df_final.drop(
  columns=['pasta_run', 'tempo_medio_execucao', 'timestamp',"Número Config"]
)

print("Resultados Finais tratados para o Dashboard")
df_final.to_excel("/home/pedrov12/Documentos/GitHub/Repopulation-With-Elite-Set/src/output/resultados.xlsx", index=False)

df_final

DataFrame final com a coluna de tempo médio:

  configuracao  execucao           timestamp      tempo_medio_execucao
0     config_1         1 2025-08-25 20:39:32 0 days 00:25:06.793650793
1     config_1         2 2025-08-25 20:39:32 0 days 00:25:06.793650793
2     config_1         3 2025-08-25 20:39:32 0 days 00:25:06.793650793
3     config_1         4 2025-08-25 20:39:32 0 days 00:25:06.793650793
4     config_2         1 2025-08-25 20:39:32    0 days 00:25:10.400000

Coluna original vs. Coluna formatada:

       tempo_medio_execucao tempo_formatado
0 0 days 00:25:06.793650793        00:25:06
1 0 days 00:25:06.793650793        00:25:06
2 0 days 00:25:06.793650793        00:25:06
3 0 days 00:25:06.793650793        00:25:06
4    0 days 00:25:10.400000        00:25:10

DF Resultados Final
Resultados Finais tratados para o Dashboard

,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,best_var_6,best_var_7,best_var_8,best_var_9,configuracao,execucao,tempo_formatado
0,0.1,0.15,20,5,5,19,52.659393,2,23,23,23,4,NaN,NaN,NaN,NaN,config_1,1,00:25:06
1,0.1,0.15,20,5,5,19,53.520267,30,4,21,21,4,NaN,NaN,NaN,NaN,config_1,2,00:25:06
2,0.1,0.15,20,5,5,19,56.019151,7,21,14,7,14,NaN,NaN,NaN,NaN,config_1,3,00:25:06
3,0.1,0.15,20,5,5,19,75.618946,26,27,28,2,28,NaN,NaN,NaN,NaN,config_1,4,00:25:06
4,0.9,0.15,20,5,5,19,83.777181,31,22,7,7,27,NaN,NaN,NaN,NaN,config_2,1,00:25:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,0.1,0.90,50,5,10,49,73.000000,1,5,3,1,4,0.0,1.0,4.0,0.0,config_4,3,00:25:10
239,0.1,0.90,50,5,10,49,528.000000,5,6,15,0,5,4.0,4.0,11.0,0.0,config_4,4,00:25:10
240,0.1,0.90,20,10,10,16,64.013561,17,0,17,5,1,0.0,17.0,0.0,11.0,config_1,1,00:25:06
241,0.5,0.90,20,10,10,6,70.031222,9,27,11,15,11,27.0,11.0,0.0,23.0,config_1,1,00:25:06
242,0.5,0.90,20,10,10,19,62.273992,3,3,3,12,9,28.0,12.0,3.0,9.0,config_1,2,00:25:06

In [ ]:
#df_final[["tempo_formatado"]].astype(int).mean()

ValueError: invalid literal for int() with base 10: '00:25:06'

## 3) Criação de tabelas e fazer seus UML com Diagrama de Classes com o uso do software

In [36]:

# tabela RCE


# Tabela AG-DEAP


# Tabela_Solutions

In [37]:
def separar_em_tabelas(df, coluna_criterio):
  """
  Separa um DataFrame em um dicionário de DataFrames menores,
  baseado nos valores únicos de uma coluna.

  Args:
    df (pd.DataFrame): O DataFrame a ser separado.
    coluna_criterio (str): O nome da coluna usada para agrupar.

  Returns:
    dict: Um dicionário onde as chaves são os valores da coluna
          e os valores são os DataFrames correspondentes.
  """
  tabelas_separadas = {}
  
  # O .groupby() cria um objeto que podemos percorrer com um loop.
  # Em cada passo, ele nos dá o nome do grupo e o DataFrame daquele grupo.
  for nome_do_grupo, df_do_grupo in df.groupby(coluna_criterio):
    # Usamos o nome do grupo como a chave do nosso dicionário
    # e guardamos o DataFrame correspondente como o valor.
    tabelas_separadas[nome_do_grupo] = df_do_grupo.copy() # .copy() evita avisos do pandas
  
  return tabelas_separadas

# --- Como usar a função ---
NUMERO_TABELS = 5 
# Vamos usar seu DataFrame final e separá-lo por 'configuracao'
dicionario_de_tabelas = separar_em_tabelas(df_final, 'configuracao')

# Agora, 'dicionario_de_tabelas' contém todas as suas tabelas separadas.
print("Tabelas criadas:", list(dicionario_de_tabelas.keys()))

for i in range(1,NUMERO_TABELS):
  df_config_1 = dicionario_de_tabelas[f'config_{i}']
  print(f"\nCabeçalho da tabela apenas para 'config_{i}':")
  display(df_config_1)

Tabelas criadas: ['config_1', 'config_2', 'config_3', 'config_4']

Cabeçalho da tabela apenas para 'config_1':

,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,best_var_6,best_var_7,best_var_8,best_var_9,configuracao,execucao,tempo_formatado
0,0.1,0.15,20,5,5,19,52.659393,2,23,23,23,4,NaN,NaN,NaN,NaN,config_1,1,00:25:06
1,0.1,0.15,20,5,5,19,53.520267,30,4,21,21,4,NaN,NaN,NaN,NaN,config_1,2,00:25:06
2,0.1,0.15,20,5,5,19,56.019151,7,21,14,7,14,NaN,NaN,NaN,NaN,config_1,3,00:25:06
3,0.1,0.15,20,5,5,19,75.618946,26,27,28,2,28,NaN,NaN,NaN,NaN,config_1,4,00:25:06
16,0.1,0.15,20,5,5,19,57.764262,20,12,2,20,4,NaN,NaN,NaN,NaN,config_1,1,00:25:06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,0.9,0.10,50,5,10,38,1468.000000,11,31,10,0,10,0.0,8.0,3.0,7.0,config_1,3,00:25:06
227,0.9,0.10,50,5,10,25,883.000000,3,0,13,15,7,19.0,7.0,1.0,2.0,config_1,4,00:25:06
240,0.1,0.90,20,10,10,16,64.013561,17,0,17,5,1,0.0,17.0,0.0,11.0,config_1,1,00:25:06
241,0.5,0.90,20,10,10,6,70.031222,9,27,11,15,11,27.0,11.0,0.0,23.0,config_1,1,00:25:06
242,0.5,0.90,20,10,10,19,62.273992,3,3,3,12,9,28.0,12.0,3.0,9.0,config_1,2,00:25:06

Cabeçalho da tabela apenas para 'config_2':

,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,best_var_6,best_var_7,best_var_8,best_var_9,configuracao,execucao,tempo_formatado
4,0.9,0.15,20,5,5,19,83.777181,31,22,7,7,27,NaN,NaN,NaN,NaN,config_2,1,00:25:10
5,0.9,0.15,20,5,5,19,77.414492,23,0,26,26,11,NaN,NaN,NaN,NaN,config_2,2,00:25:10
6,0.9,0.15,20,5,5,19,55.607796,1,7,26,1,3,NaN,NaN,NaN,NaN,config_2,3,00:25:10
7,0.9,0.15,20,5,5,19,63.419175,0,16,0,0,19,NaN,NaN,NaN,NaN,config_2,4,00:25:10
20,0.9,0.15,20,5,5,19,68.336172,31,4,8,4,4,NaN,NaN,NaN,NaN,config_2,1,00:25:10
21,0.9,0.15,20,5,5,19,68.908177,26,9,26,26,0,NaN,NaN,NaN,NaN,config_2,2,00:25:10
22,0.9,0.15,20,5,5,19,58.029117,1,15,24,1,24,NaN,NaN,NaN,NaN,config_2,3,00:25:10
23,0.9,0.15,20,5,5,19,64.770713,31,31,14,31,21,NaN,NaN,NaN,NaN,config_2,4,00:25:10
36,0.9,0.15,20,5,5,19,66.515824,8,8,28,8,23,NaN,NaN,NaN,NaN,config_2,1,00:25:10
37,0.9,0.15,20,5,5,19,89.140189,13,0,11,22,0,NaN,NaN,NaN,NaN,config_2,2,00:25:10
38,0.9,0.15,20,5,5,19,53.866939,5,26,16,5,7,NaN,NaN,NaN,NaN,config_2,3,00:25:10
39,0.9,0.15,20,5,5,19,51.160192,8,9,26,26,10,NaN,NaN,NaN,NaN,config_2,4,00:25:10
52,0.9,0.15,20,5,5,19,72.493521,2,28,2,11,23,NaN,NaN,NaN,NaN,config_2,1,00:25:10
53,0.9,0.15,20,5,5,19,66.135610,11,13,19,19,19,NaN,NaN,NaN,NaN,config_2,2,00:25:10
54,0.9,0.15,20,5,5,19,76.958566,24,0,1,11,1,NaN,NaN,NaN,NaN,config_2,3,00:25:10
55,0.9,0.15,20,5,5,19,50.877920,14,9,13,13,9,NaN,NaN,NaN,NaN,config_2,4,00:25:10
68,0.9,0.15,20,5,5,19,60.585983,28,17,28,5,28,NaN,NaN,NaN,NaN,config_2,1,00:25:10
69,0.9,0.15,20,5,5,19,78.285616,17,16,31,7,17,NaN,NaN,NaN,NaN,config_2,2,00:25:10
70,0.9,0.15,20,5,5,19,78.285616,15,14,24,8,15,NaN,NaN,NaN,NaN,config_2,3,00:25:10
71,0.9,0.15,20,5,5,19,78.229540,8,14,5,9,5,NaN,NaN,NaN,NaN,config_2,4,00:25:10
84,0.9,0.15,20,5,5,19,65.387908,26,22,7,7,23,NaN,NaN,NaN,NaN,config_2,1,00:25:10
85,0.9,0.15,20,5,5,19,50.869004,21,22,10,10,21,NaN,NaN,NaN,NaN,config_2,2,00:25:10
86,0.9,0.15,20,5,5,19,54.201161,26,21,10,10,12,NaN,NaN,NaN,NaN,config_2,3,00:25:10
87,0.9,0.15,20,5,5,19,76.783821,30,22,3,17,23,NaN,NaN,NaN,NaN,config_2,4,00:25:10
100,0.9,0.15,20,5,5,19,80.052708,31,25,4,14,6,NaN,NaN,NaN,NaN,config_2,1,00:25:10
101,0.9,0.15,20,5,5,19,52.958215,22,1,11,11,22,NaN,NaN,NaN,NaN,config_2,2,00:25:10
102,0.9,0.15,20,5,5,19,80.756886,17,26,24,25,24,NaN,NaN,NaN,NaN,config_2,3,00:25:10
103,0.9,0.15,20,5,5,19,68.367192,23,1,6,1,3,NaN,NaN,NaN,NaN,config_2,4,00:25:10
116,0.1,0.10,20,5,10,19,16.670807,8,20,18,31,2,24.0,2.0,25.0,1.0,config_2,1,00:25:10
117,0.1,0.10,20,5,10,19,15.604130,23,5,23,21,23,26.0,23.0,13.0,25.0,config_2,2,00:25:10
118,0.1,0.10,20,5,10,19,16.942936,22,29,10,30,17,3.0,10.0,13.0,12.0,config_2,3,00:25:10
119,0.1,0.10,20,5,10,19,14.994919,31,17,31,18,9,13.0,11.0,0.0,1.0,config_2,4,00:25:10
132,0.1,0.10,20,5,10,19,14.814172,8,16,1,1,30,8.0,27.0,26.0,31.0,config_2,1,00:25:10
133,0.1,0.10,20,5,10,19,15.823020,15,29,29,29,26,25.0,1.0,15.0,9.0,config_2,2,00:25:10
134,0.1,0.10,20,5,10,19,15.445063,9,31,7,27,7,23.0,5.0,28.0,11.0,config_2,3,00:25:10
135,0.1,0.10,20,5,10,19,15.151167,24,25,21,6,18,12.0,31.0,12.0,21.0,config_2,4,00:25:10
148,0.1,0.10,20,5,10,19,17.069704,15,6,0,26,31,25.0,28.0,16.0,30.0,config_2,1,00:25:10
149,0.1,0.10,20,5,10,19,14.695254,23,29,28,31,26,3.0,23.0,23.0,10.0,config_2,2,00:25:10
150,0.1,0.10,20,5,10,19,14.246364,10,30,10,8,2,9.0,12.0,30.0,8.0,config_2,3,00:25:10
151,0.1,0.10,20,5,10,19,16.669076,2,13,7,14,9,3.0,8.0,23.0,10.0,config_2,4,00:25:10
164,0.1,0.10,20,5,10,19,12.439721,18,1,18,6,23,13.0,18.0,18.0,14.0,config_2,1,00:25:10
165,0.1,0.10,20,5,10,19,17.069704,25,28,19,29,12,2.0,7.0,25.0,1.0,config_2,2,00:25:10
166,0.1,0.10,20,5,10,19,14.975233,23,1,29,29,3,29.0,9.0,10.0,3.0,config_2,3,00:25:10
167,0.1,0.10,20,5,10,19,11.150894,26,5,12,26,27,6.0,26.0,6.0,12.0,config_2,4,00:25:10
180,0.1,0.10,20,5,10,19,14.975233,16,19,26,25,22,19.0,25.0,11.0,2.0,config_2,1,00:25:10
181,0.1,0.10,20,5,10,19,15.661959,2,9,14,25,10,0.0,8.0,3.0,0.0,config_2,2,00:25:10
182,0.1,0.10,20,5,10,19,12.838618,27,10,9,27,14,9.0,5.0,14.0,11.0,config_2,3,00:25:10
183,0.1,0.10,20,5,10,19,13.966385,14,25,12,8,12,15.0,6.0,26.0,12.0,config_2,4,00:25:10
196,0.1,0.10,20,5,10,17,14.814172,25,9,27,6,15,15.0,14.0,4.0,2.0,config_2,1,00:25:10
197,0.1,0.10,20,5,10,9,16.781875,6,4,3,31,31,19.0,11.0,14.0,8.0,config_2,2,00:25:10
198,0.1,0.10,20,5,10,19,16.805406,20,1,23,24,21,26.0,24.0,20.0,21.0,config_2,3,00:25:10
199,0.1,0.10,20,5,10,7,15.704102,1,18,27,11,0,28.0,11.0,20.0,1.0,config_2,4,00:25:10
212,0.1,0.10,20,5,10,15,9.175341,9,10,5,5,9,15.0,5.0,5.0,11.0,config_2,1,00:25:10
213,0.1,0.10,20,5,10,15,15.094151,31,10,2,1,7,11.0,9.0,1.0,31.0,config_2,2,00:25:10
214,0.1,0.10,20,5,10,0,16.109138,14,29,5,22,9,6.0,0.0,0.0,14.0,config_2,3,00:25:10
215,0.1,0.10,20,5,10,2,13.126447,6,2,4,30,28,25.0,4.0,25.0,4.0,config_2,4,00:25:10
228,0.1,0.10,50,5,10,26,659.000000,8,0,1,4,6,22.0,3.0,6.0,2.0,config_2,1,00:25:10
229,0.1,0.10,50,5,10,49,1270.000000,1,9,10,1,5,15.0,7.0,4.0,14.0,config_2,2,00:25:10
230,0.1,0.10,50,5,10,45,582.000000,0,2,1,17,2,5.0,4.0,15.0,3.0,config_2,3,00:25:10
231,0.1,0.10,50,5,10,44,1130.000000,6,23,1,16,11,0.0,7.0,1.0,4.0,config_2,4,00:25:10

Cabeçalho da tabela apenas para 'config_3':

,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,best_var_6,best_var_7,best_var_8,best_var_9,configuracao,execucao,tempo_formatado
8,0.1,0.5,20,5,5,19,59.526541,28,9,28,22,28,NaN,NaN,NaN,NaN,config_3,1,00:25:10
9,0.1,0.5,20,5,5,19,73.883530,11,11,21,13,13,NaN,NaN,NaN,NaN,config_3,2,00:25:10
10,0.1,0.5,20,5,5,19,76.779690,25,24,29,12,25,NaN,NaN,NaN,NaN,config_3,3,00:25:10
11,0.1,0.5,20,5,5,19,54.100756,30,11,21,21,23,NaN,NaN,NaN,NaN,config_3,4,00:25:10
24,0.1,0.5,20,5,5,19,55.748211,2,25,25,2,25,NaN,NaN,NaN,NaN,config_3,1,00:25:10
25,0.1,0.5,20,5,5,19,71.531518,29,29,29,20,0,NaN,NaN,NaN,NaN,config_3,2,00:25:10
26,0.1,0.5,20,5,5,19,72.264769,17,16,9,21,23,NaN,NaN,NaN,NaN,config_3,3,00:25:10
27,0.1,0.5,20,5,5,19,74.790745,7,16,16,21,7,NaN,NaN,NaN,NaN,config_3,4,00:25:10
40,0.1,0.5,20,5,5,19,53.292338,16,17,25,25,27,NaN,NaN,NaN,NaN,config_3,1,00:25:10
41,0.1,0.5,20,5,5,19,53.848313,28,13,22,28,28,NaN,NaN,NaN,NaN,config_3,2,00:25:10
42,0.1,0.5,20,5,5,19,53.799338,20,1,6,20,22,NaN,NaN,NaN,NaN,config_3,3,00:25:10
43,0.1,0.5,20,5,5,19,54.646367,11,23,29,29,31,NaN,NaN,NaN,NaN,config_3,4,00:25:10
56,0.1,0.5,20,5,5,19,53.387908,26,20,8,8,21,NaN,NaN,NaN,NaN,config_3,1,00:25:10
57,0.1,0.5,20,5,5,19,53.489472,7,22,13,13,22,NaN,NaN,NaN,NaN,config_3,2,00:25:10
58,0.1,0.5,20,5,5,19,53.214548,9,19,2,2,9,NaN,NaN,NaN,NaN,config_3,3,00:25:10
59,0.1,0.5,20,5,5,19,79.524361,6,1,20,1,4,NaN,NaN,NaN,NaN,config_3,4,00:25:10
72,0.1,0.5,20,5,5,19,63.000830,11,6,11,24,7,NaN,NaN,NaN,NaN,config_3,1,00:25:10
73,0.1,0.5,20,5,5,19,60.620837,16,11,16,0,16,NaN,NaN,NaN,NaN,config_3,2,00:25:10
74,0.1,0.5,20,5,5,19,61.577501,18,10,18,5,11,NaN,NaN,NaN,NaN,config_3,3,00:25:10
75,0.1,0.5,20,5,5,19,52.958215,22,3,11,11,24,NaN,NaN,NaN,NaN,config_3,4,00:25:10
88,0.1,0.5,20,5,5,19,65.294180,13,7,14,13,14,NaN,NaN,NaN,NaN,config_3,1,00:25:10
89,0.1,0.5,20,5,5,19,67.714603,24,25,24,2,2,NaN,NaN,NaN,NaN,config_3,2,00:25:10
90,0.1,0.5,20,5,5,19,51.160192,12,12,24,24,14,NaN,NaN,NaN,NaN,config_3,3,00:25:10
91,0.1,0.5,20,5,5,19,50.869004,25,26,18,18,26,NaN,NaN,NaN,NaN,config_3,4,00:25:10
104,0.1,0.5,20,5,5,19,37.354029,0,13,0,0,2,NaN,NaN,NaN,NaN,config_3,1,00:25:10
105,0.1,0.5,20,5,5,19,68.251424,7,28,7,8,10,NaN,NaN,NaN,NaN,config_3,2,00:25:10
106,0.1,0.5,20,5,5,19,74.077808,29,30,22,3,31,NaN,NaN,NaN,NaN,config_3,3,00:25:10
107,0.1,0.5,20,5,5,19,52.909421,4,26,26,26,26,NaN,NaN,NaN,NaN,config_3,4,00:25:10
120,0.9,0.9,20,5,10,19,10.303107,16,17,3,3,5,11.0,11.0,30.0,12.0,config_3,1,00:25:10
121,0.9,0.9,20,5,10,19,12.278660,19,6,25,19,24,19.0,26.0,14.0,6.0,config_3,2,00:25:10
122,0.9,0.9,20,5,10,19,12.284799,29,7,29,16,28,27.0,28.0,30.0,8.0,config_3,3,00:25:10
123,0.9,0.9,20,5,10,19,11.998681,29,6,3,6,5,15.0,5.0,0.0,3.0,config_3,4,00:25:10
136,0.9,0.9,20,5,10,19,12.558639,0,31,5,11,17,12.0,5.0,31.0,5.0,config_3,1,00:25:10
137,0.9,0.9,20,5,10,19,9.749288,28,28,1,14,1,7.0,1.0,28.0,30.0,config_3,2,00:25:10
138,0.9,0.9,20,5,10,19,12.439721,22,0,14,1,10,15.0,1.0,10.0,10.0,config_3,3,00:25:10
139,0.9,0.9,20,5,10,19,9.463170,27,15,5,24,0,24.0,5.0,24.0,29.0,config_3,4,00:25:10
152,0.9,0.9,20,5,10,19,12.278660,4,7,14,5,4,6.0,6.0,5.0,6.0,config_3,1,00:25:10
153,0.9,0.9,20,5,10,19,12.278660,7,30,31,4,31,7.0,4.0,26.0,8.0,config_3,2,00:25:10
154,0.9,0.9,20,5,10,19,12.564953,6,28,28,6,24,31.0,29.0,31.0,28.0,config_3,3,00:25:10
155,0.9,0.9,20,5,10,19,7.207637,12,3,24,24,29,3.0,24.0,3.0,29.0,config_3,4,00:25:10
168,0.9,0.9,20,5,10,19,10.751997,20,3,20,30,5,14.0,20.0,20.0,5.0,config_3,1,00:25:10
169,0.9,0.9,20,5,10,19,8.615383,2,3,3,2,13,3.0,2.0,6.0,2.0,config_3,2,00:25:10
170,0.9,0.9,20,5,10,19,10.751997,21,0,21,3,5,8.0,3.0,0.0,29.0,config_3,3,00:25:10
171,0.9,0.9,20,5,10,19,12.451830,0,6,16,1,17,29.0,0.0,29.0,17.0,config_3,4,00:25:10
184,0.9,0.9,20,5,10,19,12.278660,4,30,19,4,31,30.0,29.0,9.0,0.0,config_3,1,00:25:10
185,0.9,0.9,20,5,10,19,11.591934,30,12,11,30,0,30.0,11.0,23.0,12.0,config_3,2,00:25:10
186,0.9,0.9,20,5,10,19,10.884611,28,18,7,17,4,2.0,2.0,18.0,2.0,config_3,3,00:25:10
187,0.9,0.9,20,5,10,19,10.870915,3,19,1,9,3,5.0,1.0,19.0,28.0,config_3,4,00:25:10
200,0.9,0.9,20,5,10,19,11.150894,27,15,27,27,10,15.0,24.0,30.0,3.0,config_3,1,00:25:10
201,0.9,0.9,20,5,10,17,13.567488,12,20,7,29,31,2.0,18.0,20.0,31.0,config_3,2,00:25:10
202,0.9,0.9,20,5,10,18,11.710852,8,8,12,7,7,29.0,7.0,29.0,13.0,config_3,3,00:25:10
203,0.9,0.9,20,5,10,17,10.303107,9,8,13,3,9,3.0,7.0,15.0,3.0,config_3,4,00:25:10
216,0.9,0.9,20,5,10,14,8.341522,0,1,0,6,7,6.0,30.0,1.0,7.0,config_3,1,00:25:10
217,0.9,0.9,20,5,10,15,12.278660,10,29,10,4,10,4.0,9.0,25.0,26.0,config_3,2,00:25:10
218,0.9,0.9,20,5,10,12,10.310957,9,2,1,28,26,1.0,9.0,25.0,30.0,config_3,3,00:25:10
219,0.9,0.9,20,5,10,-1,13.168591,22,19,24,4,24,23.0,30.0,23.0,24.0,config_3,4,00:25:10
232,0.9,0.9,50,5,10,42,244.000000,0,1,4,3,1,1.0,2.0,0.0,14.0,config_3,1,00:25:10
233,0.9,0.9,50,5,10,46,74.000000,3,0,1,0,1,5.0,5.0,3.0,0.0,config_3,2,00:25:10
234,0.9,0.9,50,5,10,47,147.000000,1,0,1,2,9,3.0,0.0,1.0,1.0,config_3,3,00:25:10
235,0.9,0.9,50,5,10,41,101.000000,3,3,1,0,0,3.0,3.0,0.0,8.0,config_3,4,00:25:10

Cabeçalho da tabela apenas para 'config_4':

,Crossover,Mutação,Número de Gerações,Tamanho População,Tamanho Individuo,Melhor Geração,best_fitness,best_var_1,best_var_2,best_var_3,best_var_4,best_var_5,best_var_6,best_var_7,best_var_8,best_var_9,configuracao,execucao,tempo_formatado
12,0.9,0.5,20,5,5,19,73.220006,28,16,0,16,18,NaN,NaN,NaN,NaN,config_4,1,00:25:10
13,0.9,0.5,20,5,5,19,78.079965,21,14,31,31,20,NaN,NaN,NaN,NaN,config_4,2,00:25:10
14,0.9,0.5,20,5,5,19,64.242341,10,23,22,22,19,NaN,NaN,NaN,NaN,config_4,3,00:25:10
15,0.9,0.5,20,5,5,19,59.561395,28,5,28,17,28,NaN,NaN,NaN,NaN,config_4,4,00:25:10
28,0.9,0.5,20,5,5,19,51.160192,11,12,25,25,12,NaN,NaN,NaN,NaN,config_4,1,00:25:10
29,0.9,0.5,20,5,5,19,66.049635,15,9,9,15,12,NaN,NaN,NaN,NaN,config_4,2,00:25:10
30,0.9,0.5,20,5,5,19,50.338217,24,30,29,24,24,NaN,NaN,NaN,NaN,config_4,3,00:25:10
31,0.9,0.5,20,5,5,19,60.677006,6,5,6,22,6,NaN,NaN,NaN,NaN,config_4,4,00:25:10
44,0.9,0.5,20,5,5,19,52.738480,25,21,25,21,27,NaN,NaN,NaN,NaN,config_4,1,00:25:10
45,0.9,0.5,20,5,5,19,53.023765,10,19,4,4,10,NaN,NaN,NaN,NaN,config_4,2,00:25:10
46,0.9,0.5,20,5,5,19,51.160192,3,4,31,31,5,NaN,NaN,NaN,NaN,config_4,3,00:25:10
47,0.9,0.5,20,5,5,19,60.585983,12,18,12,8,14,NaN,NaN,NaN,NaN,config_4,4,00:25:10
60,0.9,0.5,20,5,5,19,60.792979,3,25,3,23,25,NaN,NaN,NaN,NaN,config_4,1,00:25:10
61,0.9,0.5,20,5,5,19,50.869004,26,27,10,10,28,NaN,NaN,NaN,NaN,config_4,2,00:25:10
62,0.9,0.5,20,5,5,19,63.248430,24,19,19,23,19,NaN,NaN,NaN,NaN,config_4,3,00:25:10
63,0.9,0.5,20,5,5,19,50.783760,9,4,4,9,6,NaN,NaN,NaN,NaN,config_4,4,00:25:10
76,0.9,0.5,20,5,5,19,65.575043,25,18,23,19,19,NaN,NaN,NaN,NaN,config_4,1,00:25:10
77,0.9,0.5,20,5,5,19,53.214548,4,22,27,27,4,NaN,NaN,NaN,NaN,config_4,2,00:25:10
78,0.9,0.5,20,5,5,19,54.367143,14,14,20,14,19,NaN,NaN,NaN,NaN,config_4,3,00:25:10
79,0.9,0.5,20,5,5,19,52.666656,19,12,11,11,19,NaN,NaN,NaN,NaN,config_4,4,00:25:10
92,0.9,0.5,20,5,5,19,37.354029,24,0,24,24,26,NaN,NaN,NaN,NaN,config_4,1,00:25:10
93,0.9,0.5,20,5,5,19,54.439999,29,14,23,29,14,NaN,NaN,NaN,NaN,config_4,2,00:25:10
94,0.9,0.5,20,5,5,19,68.218846,29,12,9,11,11,NaN,NaN,NaN,NaN,config_4,3,00:25:10
95,0.9,0.5,20,5,5,19,59.337386,2,20,2,19,2,NaN,NaN,NaN,NaN,config_4,4,00:25:10
108,0.9,0.5,20,5,5,19,66.236800,7,28,7,18,20,NaN,NaN,NaN,NaN,config_4,1,00:25:10
109,0.9,0.5,20,5,5,19,54.495337,24,15,10,24,16,NaN,NaN,NaN,NaN,config_4,2,00:25:10
110,0.9,0.5,20,5,5,19,52.331675,5,23,23,23,25,NaN,NaN,NaN,NaN,config_4,3,00:25:10
111,0.9,0.5,20,5,5,19,52.034054,12,12,3,12,14,NaN,NaN,NaN,NaN,config_4,4,00:25:10
124,0.1,0.9,20,5,10,19,12.727550,9,0,9,2,4,0.0,20.0,2.0,2.0,config_4,1,00:25:10
125,0.1,0.9,20,5,10,19,10.590936,16,4,3,3,31,24.0,24.0,25.0,25.0,config_4,2,00:25:10
126,0.1,0.9,20,5,10,19,11.998681,1,4,31,31,5,9.0,4.0,6.0,1.0,config_4,3,00:25:10
127,0.1,0.9,20,5,10,19,12.838618,11,13,11,30,13,9.0,13.0,4.0,13.0,config_4,4,00:25:10
140,0.1,0.9,20,5,10,19,14.695254,22,26,15,27,17,7.0,22.0,22.0,3.0,config_4,1,00:25:10
141,0.1,0.9,20,5,10,19,12.159742,2,6,6,27,8,21.0,2.0,28.0,6.0,config_4,2,00:25:10
142,0.1,0.9,20,5,10,19,13.287508,24,29,19,24,30,6.0,5.0,20.0,15.0,config_4,3,00:25:10
143,0.1,0.9,20,5,10,19,11.718693,29,24,8,24,8,30.0,30.0,12.0,14.0,config_4,4,00:25:10
156,0.1,0.9,20,5,10,19,12.901408,20,24,5,20,30,6.0,20.0,24.0,1.0,config_4,1,00:25:10
157,0.1,0.9,20,5,10,19,11.998681,3,28,16,2,24,4.0,4.0,28.0,3.0,config_4,2,00:25:10
158,0.1,0.9,20,5,10,19,13.406426,31,8,0,31,6,7.0,0.0,3.0,5.0,config_4,3,00:25:10
159,0.1,0.9,20,5,10,19,11.998681,28,14,1,1,26,26.0,25.0,14.0,28.0,config_4,4,00:25:10
172,0.1,0.9,20,5,10,19,14.423099,26,3,8,0,22,3.0,28.0,27.0,22.0,config_4,1,00:25:10
173,0.1,0.9,20,5,10,19,12.564779,10,10,10,15,1,10.0,25.0,29.0,15.0,config_4,2,00:25:10
174,0.1,0.9,20,5,10,19,10.877082,31,5,16,16,0,5.0,4.0,6.0,27.0,config_4,3,00:25:10
175,0.1,0.9,20,5,10,19,9.463170,31,12,24,31,24,12.0,31.0,1.0,5.0,config_4,4,00:25:10
188,0.1,0.9,20,5,10,19,11.710852,19,10,2,30,26,10.0,11.0,10.0,26.0,config_4,1,00:25:10
189,0.1,0.9,20,5,10,19,13.406426,0,1,24,7,0,11.0,6.0,7.0,31.0,config_4,2,00:25:10
190,0.1,0.9,20,5,10,19,11.998681,2,0,15,28,4,0.0,26.0,2.0,28.0,config_4,3,00:25:10
191,0.1,0.9,20,5,10,19,11.606098,22,25,9,22,2,24.0,24.0,25.0,25.0,config_4,4,00:25:10
204,0.1,0.9,20,5,10,8,10.590936,24,5,17,29,4,24.0,24.0,30.0,4.0,config_4,1,00:25:10
205,0.1,0.9,20,5,10,19,8.615383,30,19,24,30,24,19.0,24.0,28.0,30.0,config_4,2,00:25:10
206,0.1,0.9,20,5,10,17,7.501294,2,24,8,8,10,24.0,8.0,3.0,10.0,config_4,3,00:25:10
207,0.1,0.9,20,5,10,17,9.183190,25,26,20,25,31,30.0,20.0,24.0,31.0,config_4,4,00:25:10
220,0.1,0.9,20,5,10,9,12.846468,2,24,1,3,5,12.0,2.0,24.0,4.0,config_4,1,00:25:10
221,0.1,0.9,20,5,10,7,12.278660,6,7,11,6,7,3.0,17.0,29.0,4.0,config_4,2,00:25:10
222,0.1,0.9,20,5,10,19,11.150894,31,15,31,26,24,26.0,26.0,26.0,11.0,config_4,3,00:25:10
223,0.1,0.9,20,5,10,17,10.590936,29,30,29,0,9,25.0,0.0,1.0,26.0,config_4,4,00:25:10
236,0.1,0.9,50,5,10,44,127.000000,1,5,7,3,1,2.0,0.0,3.0,2.0,config_4,1,00:25:10
237,0.1,0.9,50,5,10,49,140.000000,1,4,3,6,4,1.0,0.0,0.0,5.0,config_4,2,00:25:10
238,0.1,0.9,50,5,10,49,73.000000,1,5,3,1,4,0.0,1.0,4.0,0.0,config_4,3,00:25:10
239,0.1,0.9,50,5,10,49,528.000000,5,6,15,0,5,4.0,4.0,11.0,0.0,config_4,4,00:25:10

## 3) Análisando os parametros AG

In [38]:
def display_value_counts(df, column_name):
    return df[column_name].value_counts()


print("Total de execuções pelo Laucher.py", df_final.shape[0])
print("Colunas do DataFrame",df_final.columns)

display(display_value_counts(df_final, 'Crossover'))
display(display_value_counts(df_final, 'Mutação'))
display(display_value_counts(df_final, 'Número de Gerações'))
display(display_value_counts(df_final, 'Tamanho População'))
display(display_value_counts(df_final, 'Melhor Geração'))

Total de execuções pelo Laucher.py 243
Colunas do DataFrame Index(['Crossover', 'Mutação', 'Número de Gerações', 'Tamanho População',
       'Tamanho Individuo', 'Melhor Geração', 'best_fitness', 'best_var_1',
       'best_var_2', 'best_var_3', 'best_var_4', 'best_var_5', 'best_var_6',
       'best_var_7', 'best_var_8', 'best_var_9', 'configuracao', 'execucao',
       'tempo_formatado'],
      dtype='object')

Crossover
0.1    121
0.9    120
0.5      2
Name: count, dtype: int64

Mutação
0.90    67
0.10    64
0.50    56
0.15    56
Name: count, dtype: int64

Número de Gerações
20    227
50     16
Name: count, dtype: int64

Tamanho População
5     240
10      3
Name: count, dtype: int64

Melhor Geração
 19    197
 17      8
 49      5
 0       3
 15      3
 10      2
 12      2
 42      2
 9       2
 7       2
 44      2
 11      1
 18      1
 8       1
-1       1
 14      1
 38      1
 2       1
 25      1
 26      1
 45      1
 46      1
 47      1
 41      1
 16      1
 6       1
Name: count, dtype: int64

## 4) Análisando os parametros RCE

## 4 fitness functions

## Config params.json to 20x executions

## Simulate Pandapower network